/*
EECS 348 Assignment 1
Description:
    C program that picks a secret number between 1 and 10
    The user gets up to 3 tries to guess the number

There are no inputs in this program

Example Output:
Guess a number between 1 and 10.
Attempt 1/3. Enter your guess: 5
Too low! Try again.
Attempt 2/3. Enter your guess: 8
Too high! Try again.
Attempt 3/3. Enter your guess: 7
Correct! You win!

Author(s): Jun Brewer
Sources: Gemini, Claude, W3Schools
Creation date: 2026/09/07
No revisions has been made to this program thus far
*/

#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>

// this error checking function was generated by Claude
// this function makes sure that the user input is a positive whole number (not a float or letter)
// it takes in the guess and outputs true / false (1/0)
int read_valid_guess(int *guess) {
    char buffer[100];

    // separates each tokens by white space. If it doesn't read exactly 1 token, it will return invalid
    if (scanf("%99s", buffer) != 1) {
        // clear the bad input from the buffer
        // getchar() eats all inputs in the buffer until it hits a newline char or getchar outputs EOF
        while (getchar() != '\n' && getchar() != EOF);
        return 0; // read failure
    }

    // Check every character is a digit (handles "5.5", "abc", "5a", etc.)
    // loops until it hits '\0' indicating the end of the string
    for (int i = 0; buffer[i] != '\0'; i++) {
        // checking if it is a digit
        if (!isdigit((unsigned char)buffer[i])) {
            return 0; // not a clean integer
        }
    }

    // converts the now safe string into an int
    *guess = atoi(buffer);
    return 1; // returns valid
}

// All main functionality of program is generated by Gemini (everything excluding error checking)
int main() {

    // initializing values (consts are all caps)
    const int SECRET_NUMBER = 7;
    const int MAX_ATTEMPTS = 3;
    // keeps track of how many guesses the player has made
    int guess;
    // keeps track of if the user has won or not
    int guessed_correctly = 0;

    printf("Guess a number between 1 and 10.\n");

    // the progam loops until the user guess correctly or is out of attempts
    for (int attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {

        printf("Attempt %d/%d. Enter your guess: ", attempt, MAX_ATTEMPTS);

        // makes sure that input is a whole number
        if (!read_valid_guess(&guess)) {
            printf("Invalid input. Please enter a whole number.\n");
            attempt--; // don't count this as a used attempt
            continue;
        }

        // makes sure the number is in range
        if (guess < 1 || guess > 10) {
            printf("Please guess a number between 1 and 10.\n");
            attempt--; // don't count this as a used attempt
            continue;
        }

        // if user guesses correctly
        if (guess == SECRET_NUMBER) {
            printf("Correct! You win!\n");
            // switches the state so the user wins
            guessed_correctly = 1;
            break; // Stop the loop immediately on a correct guess

        // if user guesses lower than the secret number
        } else if (guess < SECRET_NUMBER) {
            //only shows text below if user have attempts left
            if (attempt < MAX_ATTEMPTS) {
                printf("Too low! Try again.\n");
            }
        // if user guesses higher than the secret number
        } else {
            //only shows text below if user have attempts left
            if (attempt < MAX_ATTEMPTS) {
                printf("Too high! Try again.\n");
            }
        }
    }

    // text that runs if the player is out of attempts
    if (!guessed_correctly) {
        printf("Out of attempts! You lose. The secret number was %d.\n", SECRET_NUMBER);
    }

    return 0;
}